### PR TITLE
make kubelet version configurable

### PR DESCRIPTION
**Pull request by yugui**

### CODE REVIEW

**Comment by aespinosa** [comment]
Thanks for the contribution.

However, I prefer extracting the version from the URL or binary instead like the one described in http://jtimberman.housepub.org/blog/2014/02/01/evolution-of-cookbook-development/

**Comment by yugui** [comment]
@aespinosa 
Actually `version` was just a way to let users easily configure the URL.
But it makes sense to let them specify URL itself.

I'll send another PR with this way.

**Comment by aespinosa** [comment]
Thanks for offering to help @yugui . If you have time to work on that I don't mind reviewing the implementation.

Off the top of my head I can see two approaches: (1) from the version string in the URL and (2) from the `--version` flag after downloading the binary.

**Comment by yugui** [comment]
@aespinosa 
I'm saying we don't actually need `version` itself here.  We just need an URL to download.
And `version` was just a way to easily specify the URL with less typing.
But it makes sense to let users specify the URL itself because it is more flexible.

**Comment by aespinosa** [comment]
Ah I see. For that purpose yes it is not needed.

**Comment by yugui** [comment]
Pushed #4

**Pull request closed without merging**
